[package]
name = "vulkan"
version = "0.1.0"
authors = ["mobile-bungalow <pwmay@ucsc.edu>"]
edition = "2018"

[dependencies]
vulkano = "0.11"
vulkano-shaders = "0.11"
vulkano-win = "0.11"
cgmath = "0.17"
image = "0.20"
winit = "0.18"
tobj = "0.1.7"
clap = "2.33.0"




